package Helloapl;


/**
* Helloapl/hello.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/estaf/.eclipse/eclipse-workspace/dsd/src/hello.idl
* Sunday, July 7, 2019 10:36:54 o'clock PM EDT
*/

public interface hello extends helloOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface hello
