package Helloapl;

/**
* Helloapl/helloHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/estaf/.eclipse/eclipse-workspace/dsd/src/hello.idl
* Sunday, July 7, 2019 10:36:54 o'clock PM EDT
*/

public final class helloHolder implements org.omg.CORBA.portable.Streamable
{
  public Helloapl.hello value = null;

  public helloHolder ()
  {
  }

  public helloHolder (Helloapl.hello initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Helloapl.helloHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Helloapl.helloHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Helloapl.helloHelper.type ();
  }

}
