package Helloapl;


/**
* Helloapl/helloHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/estaf/.eclipse/eclipse-workspace/dsd/src/hello.idl
* Sunday, July 7, 2019 10:36:54 o'clock PM EDT
*/

abstract public class helloHelper
{
  private static String  _id = "IDL:Helloapl/hello:1.0";

  public static void insert (org.omg.CORBA.Any a, Helloapl.hello that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Helloapl.hello extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (Helloapl.helloHelper.id (), "hello");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Helloapl.hello read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_helloStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Helloapl.hello value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Helloapl.hello narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Helloapl.hello)
      return (Helloapl.hello)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Helloapl._helloStub stub = new Helloapl._helloStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Helloapl.hello unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Helloapl.hello)
      return (Helloapl.hello)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Helloapl._helloStub stub = new Helloapl._helloStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
